const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Shape3D,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Eventosjogo_Event15_Act2,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Eventostelainicio_Event3_Act1,
		C3.JavaScriptInEvents.Eventosgameover_Event1_Act1,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{céu: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Sprite: 0},
	{chao: 0},
	{vida: 0},
	{atacando: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{ninja: 0},
	{Teclado: 0},
	{predios: 0},
	{cidade2: 0},
	{prediso2: 0},
	{Áudio: 0},
	{céu2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{FonteDeSprites: 0},
	{Forma3D: 0},
	{FonteDeSprites2: 0},
	{btPlay: 0},
	{Mouse: 0},
	{vidazumbi: 0},
	{zumbiMale: 0},
	{Sprite4: 0},
	{gameOver: 0},
	{Sprite5: 0},
	{playAgain: 0},
	{vidaNinja: 0},
	{barraVida: 0},
	{VIDA: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	céu: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	ninja: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	predios: class extends self.ISpriteInstance {},
	cidade2: class extends self.ISpriteInstance {},
	prediso2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	céu2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Forma3D: class extends self.I3DShapeInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	btPlay: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	zumbiMale: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteFontInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	playAgain: class extends self.ISpriteFontInstance {},
	vidaNinja: class extends self.ISpriteFontInstance {},
	barraVida: class extends self.ISpriteInstance {},
	VIDA: class extends self.ISpriteFontInstance {}
}